import type { LandingPagePuckData } from './types'

const ourWorkLogos = [
  { src: '/client-logos/19.png', name: 'DEZ', category: 'B2B systems' },
  { src: '/client-logos/20.png', name: 'Dr. Mohamed Hany Mahour', category: 'Healthcare' },
  { src: '/client-logos/21.png', name: 'Mas Eye Center', category: 'Healthcare', size: 'wide' as const },
  { src: '/client-logos/22.png', name: 'Grease Monkey', category: 'Retail services', size: 'wide' as const },
  { src: '/client-logos/23.png', name: 'Radio', category: 'Consumer' },
  { src: '/client-logos/24.png', name: 'Osama Taha', category: 'Healthcare' },
  { src: '/client-logos/25.png', name: 'Tag', category: 'Personal care', size: 'tall' as const },
  { src: '/client-logos/26.png', name: 'GIG Insurance Group', category: 'Insurance' },
  { src: '/client-logos/27.png', name: 'Shaden Resort', category: 'Hospitality', size: 'tall' as const },
  { src: '/client-logos/28.png', name: 'Movenpick Hotel & Residences Riyadh', category: 'Hospitality', size: 'wide' as const },
  { src: '/client-logos/29.png', name: 'Grand Millennium Dubai', category: 'Hospitality', size: 'tall' as const },
  { src: '/client-logos/30.png', name: 'Sun Stall', category: 'Retail' },
  { src: '/client-logos/31.png', name: 'Belmazad', category: 'Marketplace', size: 'wide' as const },
  { src: '/client-logos/32.png', name: 'Porto Vacation Club', category: 'Travel' },
  { src: '/client-logos/33.png', name: 'ABRO', category: 'Automotive', size: 'wide' as const },
  { src: '/client-logos/34.png', name: 'Amer Group', category: 'Real estate', size: 'wide' as const },
  { src: '/client-logos/35.png', name: 'Madinet Masr', category: 'Real estate', size: 'wide' as const },
]

export const DEFAULT_ROOT_PROPS = {
  title: 'Miduva landing page',
  defaultTheme: 'dark' as const,
  seo: {
    title: 'Miduva — We Build Custom Growth Systems',
    description:
      'No generic services. We design tailored systems using ads, funnels, automation & data to grow your business — engineered end-to-end, owned by you.',
  },
  branding: {
    logoDarkUrl: '/assets/miduva-logo.png',
    logoLightUrl: '/assets/miduva-logo-white.png',
    logoAlt: 'Miduva',
  },
  nav: {
    leftLinks: [
      { label: 'Services', href: '#services' },
      { label: 'Systems', href: '#systems' },
      { label: 'How it Works', href: '#how-it-works' },
    ],
    rightLinks: [
      { label: 'Our Work', href: '#our-work' },
      { label: 'About', href: '#why-miduva' },
      { label: 'Get Started', href: '#cta' },
    ],
  },
  dashboard: {
    urlLabel: 'app.miduva.systems / growth-os',
    statusLabel: 'LIVE',
    syncLabel: 'synced 12s ago',
    systemLabel: 'System',
    clientsLabel: 'Clients',
    navItems: ['Overview', 'Ads', 'Funnels', 'Automation', 'Data', 'Reports'],
    clients: [
      { initials: 'AR', name: 'Arvo Labs' },
      { initials: 'NV', name: 'Novae' },
      { initials: 'KL', name: 'Kilo & Co' },
    ],
    eyebrow: 'Growth System · Arvo Labs',
    title: 'Q2 Performance Overview',
    rangeLabels: ['7d', '30d', 'QTD', 'YTD'],
    activeRangeIndex: 2,
    kpis: [
      { label: 'Qualified Leads', value: '1,284', delta: '+38%', color: 'teal' as const },
      { label: 'Pipeline', value: '$482K', delta: '+21%', color: 'navy' as const },
      { label: 'ROAS', value: '5.2×', delta: '+0.8×', color: 'teal' as const },
      { label: 'CAC', value: '$41', delta: '-29%', color: 'navy' as const },
    ],
    chartTitle: 'Lead flow · last 12 weeks',
    chartSubtitle: 'Paid + Organic + Automation',
    chartLegend: ['Paid', 'Organic', 'Nurture'],
    chartAxisLabels: ['1.2k', '800', '400', '0'],
    chartWeekLabels: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7', 'W8', 'W9', 'W10', 'W11', 'W12'],
    chartValues: [42, 58, 51, 64, 72, 69, 81, 88, 83, 92, 97, 104],
    funnelTitle: 'Funnel health',
    funnelStages: [
      { name: 'Visitors', value: '48,210' },
      { name: 'Engaged', value: '12,882' },
      { name: 'Leads', value: '3,104' },
      { name: 'SQLs', value: '1,284' },
      { name: 'Closed-won', value: '184' },
    ],
    optimizedLabel: 'optimized',
    automationLabel: 'Automation health',
    automationHealth: 96,
  },
}

export const DEFAULT_SECTION_PROPS = {
  HeroSection: {
    headline: 'We build custom growth systems.',
    tagline: 'A system that learns, adapts, and accelerates your growth.',
    body: 'No generic services. We design tailored systems using ads, funnels, automation, and data — engineered end-to-end, owned by you.',
    phrasePrefix: 'Engineered to',
    phrases: ['generate leads.', 'drive sales.', 'scale your business.'],
    primaryCta: { label: 'Get Started', href: '#get-started' },
    secondaryCta: { label: 'See Our Work', href: '#our-work' },
    illustrationDarkUrl: '/assets/system-dark.png',
    illustrationLightUrl: '/assets/system-light.png',
    illustrationAlt: 'Miduva growth system interface',
  },
  SystemsSection: {
    eyebrow: '/ our systems',
    headline: 'Three systems.',
    headlineAccent: 'One growth machine.',
    ctaLabel: 'Explore Your System',
    ctaHref: '#cta',
    systems: [
      { id: 'lead-gen', num: '01', label: 'Lead Generation System', title: 'Consistent leads.\nOn autopilot.', description: 'Generate predictable lead flow using ads, funnels & precision conversion systems built for your market.', imageUrl: '/assets/systems/lead-gen.jpg' },
      { id: 'website-conversion', num: '02', label: 'Website & Conversion System', title: 'Your website,\nactually converting.', description: "Turn traffic into revenue with a high-performance site engineered around your buyer's journey.", imageUrl: '/assets/systems/website-conversion.jpg' },
      { id: 'automation', num: '03', label: 'Smart Automation System', title: 'Sales & follow-ups\nrunning 24/7.', description: 'CRM workflows, AI agents, and email sequences that close deals while you sleep, no extra hires.', imageUrl: '/assets/systems/automation.jpg' },
    ],
    backgroundImages: [
      { url: '/assets/systems/bg-growth.jpg', alt: 'Growth dashboard visualization' },
      { url: '/assets/systems/bg-web.jpg', alt: 'Website conversion interface' },
      { url: '/assets/systems/bg-data.jpg', alt: 'Data analytics workspace' },
      { url: '/assets/systems/bg-automation.jpg', alt: 'Automation workflow interface' },
      { url: '/assets/systems/bg-digital.jpg', alt: 'Digital campaign interface' },
      { url: '/assets/systems/bg-charts.jpg', alt: 'Performance chart visualization' },
    ],
  },
  ProblemSolutionSection: {
    problemEyebrow: '/ the problem',
    problemHeadline: 'Three traps that kill growth.',
    problems: [
      { id: 'ads', num: '01', label: 'Trap 01', title: 'Traffic that goes nowhere', detail: "You're buying clicks. Not customers. Your ad spend is a leaky bucket.", icon: 'close' as const },
      { id: 'traffic', num: '02', label: 'Trap 02', title: 'Visitors that bounce', detail: 'People land, scan, leave. No funnel. No follow-up. No revenue.', icon: 'alert' as const },
      { id: 'leads', num: '03', label: 'Trap 03', title: 'Leads that go cold', detail: 'Hot prospects slip through the cracks. No system to catch them.', icon: 'close' as const },
    ],
    solution: {
      headline: 'One system.',
      headlineAccent: 'Zero gaps.',
      subheadline: 'We build the machine that fixes all three traps.',
      bullets: ['Ads engineered to attract ready buyers', 'Funnels built to convert, not decorate', 'Automation that nurtures while you sleep'],
      ctaLabel: 'See How It Works',
      ctaHref: '#cta',
      bottomNote: 'One connected machine. End-to-end.',
    },
  },
  HowItWorksSection: {
    eyebrow: '/ how it works',
    headline: 'From audit to scale —',
    headlineAccent: 'four steps.',
    steps: [
      { id: 'analyze', num: '01', title: 'Analyze Your Business', description: 'We audit your channels, funnels, and conversion gaps to build a complete picture of where you stand and where the biggest opportunities hide.', imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop' },
      { id: 'strategy', num: '02', title: 'Build a Custom Strategy', description: 'A system blueprint tailored to your market, audience, and goals — no templates, no guesswork, just a clear plan for growth.', imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2670&auto=format&fit=crop' },
      { id: 'launch', num: '03', title: 'Launch & Optimize the System', description: 'Everything goes live and gets tuned until it performs. We test, iterate, and refine until every metric is moving in the right direction.', imageUrl: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?q=80&w=2670&auto=format&fit=crop' },
      { id: 'scale', num: '04', title: 'Scale Your Results', description: 'More traffic, better conversions, automated follow-up — compounding returns that grow your business while you focus on what you do best.', imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop' },
    ],
  },
  ResultsSection: {
    eyebrow: '/ results',
    headline: "Numbers don't lie.",
    subheadline: 'Aggregated across all active client systems.\nMeasured. Verified. Repeatable.',
    stats: [
      { id: 'leads', value: 120, suffix: '+', label: 'Leads Generated', sub: 'Per client, per quarter on average' },
      { id: 'conversion', value: 3, suffix: '×', label: 'Conversion Rate', sub: 'Compared to industry baseline' },
      { id: 'cpl', value: 40, suffix: '%', label: 'Lower Cost per Lead', sub: 'After full system optimization' },
    ],
    trustNote: 'All metrics averaged across Q1–Q2 client cohorts',
    ctaLabel: 'Get your free growth plan',
    ctaHref: '#cta',
  },
  OurWorkSection: {
    eyebrow: '/ our clients',
    headline: 'Selected client systems.',
    ariaLabel: 'Selected Miduva client logos',
    logos: ourWorkLogos,
  },
  WhyMiduvaSection: {
    eyebrow: 'Why Miduva',
    watermark: 'WHY',
    statementLead: "We don't sell",
    statementOldWay: 'services.',
    statementBridge: 'We build',
    statementAccent: 'systems',
    statementTail: 'designed to grow your business.',
    wideStatValue: '4.8×',
    wideStatLabel: 'Avg. ROAS',
    differentiators: [
      { id: 'custom', num: '01', title: 'Custom Solutions', subtitle: 'Tailored architecture', oldWay: 'cookie-cutter packages', newWay: 'systems built around your business' },
      { id: 'data', num: '02', title: 'Data-Driven Decisions', subtitle: 'Quantified strategy', oldWay: 'gut-feel strategy', newWay: 'every move backed by real numbers' },
      { id: 'ai', num: '03', title: 'AI-Powered Systems', subtitle: 'Intelligent automation', oldWay: 'manual, repetitive tasks', newWay: 'AI agents running the heavy lifting' },
      { id: 'roi', num: '04', title: 'Focus on ROI', subtitle: 'Revenue-first metrics', oldWay: 'vanity metrics and reports', newWay: 'revenue impact, measured and proven' },
    ],
  },
  ParallaxSection: {
    eyebrow: 'The Miduva Difference',
    headline: 'Built as a',
    headlineAccent: 'system.',
    description: 'Not a one-off campaign, not a template. A connected machine — ads → funnels → automation → data — tuned for your business.',
    pipelineLabel: 'Pipeline · live',
    pipelineValue: '$482,120',
    pipelineDelta: '▲ 21.4%',
    pipelineComparison: 'vs last Q',
    chartValues: [42, 58, 51, 64, 72, 69, 81, 88, 83, 92, 97, 104],
    bottomLabel: 'Eight modules · one OS',
    bottomDescription: 'Every lever connected, every number visible, every dollar accounted for.',
  },
  ServicesSection: {
    eyebrow: '/ what we do',
    headline: 'Everything you need',
    headlineAccent: 'to grow.',
    activeLabel: 'Active system',
    servicesLabel: 'services',
    ctaLabel: 'Book a free strategy call',
    ctaHref: '#cta',
    categories: [
      { id: 'growth-marketing', title: 'Growth & Marketing', items: ['Paid Ads', 'Social Media Ads', 'Retargeting', 'SEO', 'Content Marketing', 'AI Visibility (GEO)', 'Advanced Growth Strategies'], imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=900&auto=format&fit=crop' },
      { id: 'conversion-funnels', title: 'Conversion & Funnels', items: ['Landing Pages', 'Sales Funnels', 'CRO', 'A/B Testing', 'UX Optimization', 'Personalization Systems'], imageUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=900&auto=format&fit=crop' },
      { id: 'websites-dev', title: 'Websites & Development', items: ['Landing Pages', 'E-Commerce', 'Performance Optimization', 'CMS', 'Web Apps', 'SaaS Development'], imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=900&auto=format&fit=crop' },
      { id: 'ecommerce', title: 'E-Commerce', items: ['Shopify', 'WooCommerce', 'Custom Platforms', 'Marketing Integration', 'Conversion Optimization'], imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=900&auto=format&fit=crop' },
      { id: 'ai-automation', title: 'AI & Automation', items: ['WhatsApp & Website Chatbots', 'CRM Automation', 'Email Automation', 'Lead Management', 'AI Sales Agents', 'n8n Workflows', 'Custom AI'], imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=900&auto=format&fit=crop' },
      { id: 'data-analytics', title: 'Data & Analytics', items: ['GA4 / Meta Setup', 'Conversion Tracking', 'Dashboards', 'Reporting', 'Attribution Modeling', 'Revenue Forecasting'], imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=900&auto=format&fit=crop' },
    ],
  },
  GrowthOsSection: {
    eyebrow: '/ growth os',
    headline: 'Six modules.',
    headlineAccent: 'One connected system.',
    description: 'Every lever connected, every number visible, every dollar accounted for.',
    ctaLabel: 'See how we build it',
    ctaHref: '#cta',
    modules: [
      { name: 'Paid Ads', tag: 'Meta · Google · TikTok', description: 'Multi-channel acquisition tuned for CAC efficiency.', color: 'teal' as const, span: 2 as const, visual: 'bars' as const },
      { name: 'Funnel Design', tag: 'High-converting flows', description: 'Landing pages & flows that turn clicks into SQLs.', color: 'navy' as const, span: 1 as const, visual: 'funnel' as const },
      { name: 'Automation', tag: 'Sequences & triggers', description: 'Smart nurture that responds to behaviour in real time.', color: 'teal' as const, span: 1 as const, visual: 'nodes' as const },
      { name: 'CRM & Data', tag: 'Pipeline · attribution', description: 'Clean data architecture with full-funnel visibility.', color: 'navy' as const, span: 2 as const, visual: 'grid' as const },
      { name: 'Lead Scoring', tag: 'Qualify & prioritise', description: 'AI-ranked leads so sales always knows who to call.', color: 'teal' as const, span: 2 as const, visual: 'rings' as const },
      { name: 'Analytics', tag: 'Live · actionable', description: 'No vanity metrics. Just decisions that move revenue.', color: 'navy' as const, span: 1 as const, visual: 'spark' as const },
    ],
  },
  FaqSection: {
    eyebrow: 'Common questions',
    headline: 'What founders ask before they book.',
    body: "If your question isn't here, it will be in the call.",
    items: [
      { id: 'different', num: '01', question: 'How is Miduva different from a traditional marketing agency?', answer: 'Traditional agencies sell services: ad management, email sequences, content calendars. Miduva builds the infrastructure those services run on. We design a complete acquisition and conversion system, wire it together across your channels, and hand it to you fully owned. When the engagement ends, the system keeps running without us.' },
      { id: 'specialize', num: '02', question: 'Do you work with any business, or do you specialize?', answer: "We work best with B2B SaaS companies and DTC brands generating between $1M and $30M in annual revenue. At that stage, there's enough volume to optimize against and enough complexity to warrant a system. Earlier-stage companies often need a different approach, and we'll say so upfront rather than take the engagement." },
      { id: 'first30', num: '03', question: 'What does the first 30 days actually look like?', answer: "We start with a full audit: current channels, funnel performance, conversion rates, and attribution. In week two, you receive a system blueprint, a prioritized roadmap, and the baseline KPIs we'll measure against. By day 30, the first components are live and generating real data. No 90-day ramp-up periods." },
      { id: 'timeline', num: '04', question: 'How quickly will I see results?', answer: "Most clients see measurable changes within 30 to 60 days. Meaningful ROI, the kind you'd present in a board meeting, typically lands in the 60 to 90 day window as the system compounds. We put these expectations in writing before we start, not after a quarter passes." },
      { id: 'performance', num: '05', question: "What if the system doesn't perform?", answer: "We build in checkpoints at 30, 60, and 90 days. If a component isn't hitting its benchmark, we diagnose and rebuild it, not add more budget to something broken. Every system ships with defined success criteria, and we hold ourselves to those, not to billable-hour targets." },
      { id: 'budget', num: '06', question: 'Do I need a large budget to get started?', answer: "We don't have a fixed minimum, but we do require an existing audience or traffic source to work with. Cold-start growth from zero is a different playbook. If you're already generating leads or revenue and want to systematize and scale, we're likely a strong fit." },
      { id: 'team', num: '07', question: 'Will I need to hire a team to manage what you build?', answer: "No. Operational independence is a design constraint on every system we build. It should run with minimal ongoing management from your side. We document everything, train your team on the parts that matter, and design for the scenario where we're no longer involved." },
      { id: 'ownership', num: '08', question: "What does 'owned by you' mean in practice?", answer: 'Every tool, account, campaign, and automation lives in your accounts from day one. No proprietary platforms, no locked dashboards, no client portal we control. If you want to bring operations in-house or hand the system to another team, you can. We have no lock-in incentive.' },
    ],
  },
  FreeOfferSection: {
    eyebrow: '/ free offer',
    headlineLine1: 'Get a Free',
    headlineAccent: 'Growth Strategy',
    headlineLine3: 'for Your Business.',
    includes: ['Full Business Audit', 'Custom Growth Plan', 'Expert Recommendations'],
    ctaLabel: 'Book Your Free Call',
    ctaHref: '#cta',
    trustNote: 'No commitment · No credit card · Just real strategy',
  },
  ContactSection: {
    eyebrow: '/ get in touch',
    headline: "Let's build something",
    headlineAccent: 'that actually works.',
    body: "Tell us about your business. We'll review your situation and respond with a tailored plan — not a sales pitch.",
    contactInfo: [{ icon: 'mail' as const, label: 'hello@miduva.com' }, { icon: 'building' as const, label: 'Available Worldwide · Remote-First' }],
    trustStats: [{ stat: '4.8×', label: 'Average ROAS' }, { stat: '+312%', label: 'Lead Volume' }, { stat: '14 days', label: 'Time to Launch' }, { stat: '94%', label: 'Client Retention' }],
    formHeadline: 'Start the conversation',
    formSubheadline: 'We respond within 24 hours · No spam, ever',
    nameLabel: 'Full Name', namePlaceholder: 'Your name',
    emailLabel: 'Email Address', emailPlaceholder: 'you@company.com',
    companyLabel: 'Company (Optional)', companyPlaceholder: 'Company name',
    serviceLabel: 'Service Interest', servicePlaceholder: 'Select a service...',
    messageLabel: 'Your Message', messagePlaceholder: 'Tell us what you need help with...',
    serviceOptions: [
      { value: '', label: 'Select a service...' }, { value: 'growth-marketing', label: 'Growth & Marketing' },
      { value: 'conversion-funnels', label: 'Conversion & Funnels' }, { value: 'websites-dev', label: 'Websites & Development' },
      { value: 'ecommerce', label: 'E-Commerce' }, { value: 'ai-automation', label: 'AI & Automation' },
      { value: 'data-analytics', label: 'Data & Analytics' }, { value: 'full-system', label: 'Full Growth System' },
    ],
    submitLabel: 'Send Message',
    submittingLabel: 'Sending...',
    finePrint: 'No commitment · No credit card · 100% Confidential',
    successHeadline: 'Message Sent.',
    successBody: "We'll be in touch within 24 hours with a tailored plan — not a sales pitch.",
    resetLabel: 'Send another message',
    errorMessage: 'We could not send your message. Please try again.',
    nameRequiredMessage: 'Name is required', emailRequiredMessage: 'Email is required', emailInvalidMessage: 'Enter a valid email',
    serviceRequiredMessage: 'Please select a service', messageRequiredMessage: 'Message is required', messageTooShortMessage: 'Please write at least 20 characters',
  },
  FooterSection: {
    giantBgText: 'MIDUVA',
    heading: 'Ready to grow?',
    marqueeItems: ['More Leads, Less Effort', '4.8× ROAS Guaranteed', 'Launch in 14 Days', '94% Client Retention', 'Done-For-You Systems'],
    primaryCtas: [{ label: 'Book a Free Call', href: '#' }, { label: 'Get Started', href: '#' }],
    secondaryLinks: [{ label: 'Privacy Policy', href: '#' }, { label: 'Terms of Service', href: '#' }, { label: 'Support', href: '#' }],
    copyright: '© 2026 Miduva. All rights reserved.',
    createdByLabel: 'Created by',
    createdByName: 'Miduva',
    backToTopLabel: 'Back to top',
  },
}

const defaultData: LandingPagePuckData = {
  content: [],
  root: {
    props: {
      ...DEFAULT_ROOT_PROPS,
      beforeDashboard: [
        { type: 'HeroSection', props: { id: 'hero-section', ...DEFAULT_SECTION_PROPS.HeroSection } },
        { type: 'SystemsSection', props: { id: 'systems-section', ...DEFAULT_SECTION_PROPS.SystemsSection } },
        { type: 'ProblemSolutionSection', props: { id: 'problem-solution-section', ...DEFAULT_SECTION_PROPS.ProblemSolutionSection } },
        { type: 'HowItWorksSection', props: { id: 'how-it-works-section', ...DEFAULT_SECTION_PROPS.HowItWorksSection } },
        { type: 'ResultsSection', props: { id: 'results-section', ...DEFAULT_SECTION_PROPS.ResultsSection } },
        { type: 'OurWorkSection', props: { id: 'our-work-section', ...DEFAULT_SECTION_PROPS.OurWorkSection } },
        { type: 'WhyMiduvaSection', props: { id: 'why-miduva-section', ...DEFAULT_SECTION_PROPS.WhyMiduvaSection } },
        { type: 'ParallaxSection', props: { id: 'parallax-section', ...DEFAULT_SECTION_PROPS.ParallaxSection } },
      ],
      afterDashboard: [
        { type: 'ServicesSection', props: { id: 'services-section', ...DEFAULT_SECTION_PROPS.ServicesSection } },
        { type: 'GrowthOsSection', props: { id: 'growth-os-section', ...DEFAULT_SECTION_PROPS.GrowthOsSection } },
        { type: 'FaqSection', props: { id: 'faq-section', ...DEFAULT_SECTION_PROPS.FaqSection } },
        { type: 'FreeOfferSection', props: { id: 'free-offer-section', ...DEFAULT_SECTION_PROPS.FreeOfferSection } },
        { type: 'ContactSection', props: { id: 'contact-section', ...DEFAULT_SECTION_PROPS.ContactSection } },
        { type: 'FooterSection', props: { id: 'footer-section', ...DEFAULT_SECTION_PROPS.FooterSection } },
      ],
    },
  },
}

export function getDefaultLandingPageData(): LandingPagePuckData {
  return structuredClone(defaultData)
}
