/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    subscribers: Subscriber;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'landing-page': LandingPage;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who can sign in to this CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage all images used across the site. Give each image a clear title so you can find it easily.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A short name so you can identify this image later (e.g. "Hero background", "Recruitment system card").
   */
  title: string;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * People who left their email on the coming-soon page. They will be notified at launch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Where the subscription was captured from.
   */
  source?: string | null;
  /**
   * Captured at submission for spam diagnostics.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted from the Start the conversation form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  /**
   * Selected service interest value from the contact form.
   */
  service: string;
  message: string;
  /**
   * Where this lead was captured from.
   */
  source?: string | null;
  /**
   * Captured at submission for spam diagnostics.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  service?: T;
  message?: T;
  source?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every section of the public landing page. Use the tabs below — they follow the order sections appear on the page, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  layout?: {
    /**
     * Drag the handle on the left to reorder. Each row is one section on the public page.
     */
    sections?:
      | {
          sectionId:
            | 'hero'
            | 'systems'
            | 'problem-solution'
            | 'how-it-works'
            | 'results'
            | 'our-work'
            | 'why-miduva'
            | 'parallax'
            | 'dashboard'
            | 'services'
            | 'growth-os'
            | 'faq'
            | 'free-offer'
            | 'contact'
            | 'footer';
          visible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Transparent PNGs. The light version is used on dark sections, the dark version on light sections.
   */
  branding?: {
    logoDark?: (number | null) | Media;
    logoLight?: (number | null) | Media;
  };
  /**
   * Links shown in the top bar. Left links sit beside the logo; right links sit on the opposite side.
   */
  nav?: {
    leftLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    rightLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  hero?: {
    /**
     * Main headline above the rotating phrases.
     */
    headline?: string | null;
    /**
     * Short line under the headline.
     */
    tagline?: string | null;
    /**
     * Paragraph below the tagline. Keep it to 1–2 sentences.
     */
    body?: string | null;
    /**
     * Words that cycle through inside the headline. Order matters.
     */
    phrases?:
      | {
          phrase: string;
          id?: string | null;
        }[]
      | null;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Shown behind hero text in dark mode. ~2400×1600px.
     */
    illustrationDark?: (number | null) | Media;
    /**
     * Shown behind hero text in light mode. ~2400×1600px.
     */
    illustrationLight?: (number | null) | Media;
  };
  systems?: {
    /**
     * Small caption above the headline.
     */
    eyebrow?: string | null;
    headline?: string | null;
    /**
     * Part of the headline rendered in accent color.
     */
    headlineAccent?: string | null;
    /**
     * One card per system. Cards expand on hover/zoom.
     */
    systems?:
      | {
          num: string;
          id: string | null;
          label: string;
          title: string;
          description?: string | null;
          /**
           * Recommended 800×600px. Shows when the card is expanded.
           */
          image?: (number | null) | Media;
        }[]
      | null;
    /**
     * The 6 images that zoom out behind the section on scroll. Order matches the on-screen position/scale, so reordering will visibly rearrange the composition.
     */
    backgroundImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  problemSolution?: {
    problemEyebrow?: string | null;
    problemHeadline?: string | null;
    problems?:
      | {
          num: string;
          id: string | null;
          label: string;
          title: string;
          detail?: string | null;
          /**
           * Icon shown on the card.
           */
          icon: 'close' | 'alert';
        }[]
      | null;
    /**
     * The bright panel on the right that answers the problems.
     */
    solution?: {
      headline?: string | null;
      headlineAccent?: string | null;
      subheadline?: string | null;
      bullets?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
      /**
       * Small line under the CTA button.
       */
      bottomNote?: string | null;
    };
  };
  results?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    /**
     * Each card animates from 0 up to the value.
     */
    stats?:
      | {
          id: string | null;
          value: number;
          /**
           * e.g. %, x, +
           */
          suffix: string;
          label: string;
          /**
           * Tiny line under the big number.
           */
          sub: string;
        }[]
      | null;
    /**
     * Small note above the CTA (e.g. "Trusted by…").
     */
    trustNote?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  parallax?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    pipelineLabel?: string | null;
    pipelineValue?: string | null;
    pipelineDelta?: string | null;
    bottomLabel?: string | null;
    bottomDescription?: string | null;
  };
  /**
   * The old-way / new-way comparison cards.
   */
  whyMiduva?: {
    eyebrow?: string | null;
    differentiators?:
      | {
          num: string;
          id: string | null;
          title: string;
          subtitle: string;
          oldWay: string;
          newWay: string;
        }[]
      | null;
  };
  howItWorks?: {
    eyebrow?: string | null;
    headline?: string | null;
    /**
     * Listed in order. Each step has a background image.
     */
    steps?:
      | {
          num: string;
          id: string | null;
          title: string;
          description?: string | null;
          /**
           * Recommended 800×600px.
           */
          image?: (number | null) | Media;
        }[]
      | null;
  };
  services?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    categories?:
      | {
          id: string | null;
          title: string;
          /**
           * Recommended 800×600px.
           */
          image?: (number | null) | Media;
          items?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  dashboard?: {
    urlLabel?: string | null;
    statusLabel?: string | null;
    navItems?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    clients?:
      | {
          initials: string;
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Small caption above title.
     */
    eyebrow?: string | null;
    title?: string | null;
    kpis?:
      | {
          label: string;
          value: string;
          delta: string;
          color: 'teal' | 'navy';
          id?: string | null;
        }[]
      | null;
    chartTitle?: string | null;
    chartSubtitle?: string | null;
    funnelTitle?: string | null;
    funnelStages?:
      | {
          name: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  growthOs?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    modules?:
      | {
          name: string;
          tag: string;
          description: string;
          color: 'teal' | 'navy';
          span: '1' | '2';
          /**
           * Chooses which SVG animation appears on the card.
           */
          visual: 'bars' | 'funnel' | 'nodes' | 'grid' | 'rings' | 'spark';
          id?: string | null;
        }[]
      | null;
  };
  freeOffer?: {
    eyebrow?: string | null;
    /**
     * e.g. "Get a Free"
     */
    headlineLine1?: string | null;
    /**
     * Accent middle line (e.g. "Growth Strategy")
     */
    headlineAccent?: string | null;
    /**
     * e.g. "for Your Business."
     */
    headlineLine3?: string | null;
    includes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    trustNote?: string | null;
  };
  contact?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    body?: string | null;
    contactInfo?:
      | {
          icon: 'mail' | 'building';
          label: string;
          id?: string | null;
        }[]
      | null;
    trustStats?:
      | {
          stat: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    formHeadline?: string | null;
    formSubheadline?: string | null;
    serviceOptions?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    finePrint?: string | null;
  };
  footer?: {
    giantBgText?: string | null;
    heading?: string | null;
    /**
     * Cycle of phrases scrolling across the top.
     */
    marqueeItems?:
      | {
          phrase: string;
          id?: string | null;
        }[]
      | null;
    primaryCtas?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    secondaryLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
    createdByLabel?: string | null;
  };
  faq?: {
    /**
     * Questions appear in the order listed here.
     */
    items?:
      | {
          num: string;
          id: string | null;
          question: string;
          answer: string;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        sections?:
          | T
          | {
              sectionId?: T;
              visible?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        logoDark?: T;
        logoLight?: T;
      };
  nav?:
    | T
    | {
        leftLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        rightLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        body?: T;
        phrases?:
          | T
          | {
              phrase?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        illustrationDark?: T;
        illustrationLight?: T;
      };
  systems?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        systems?:
          | T
          | {
              num?: T;
              id?: T;
              label?: T;
              title?: T;
              description?: T;
              image?: T;
            };
        backgroundImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  problemSolution?:
    | T
    | {
        problemEyebrow?: T;
        problemHeadline?: T;
        problems?:
          | T
          | {
              num?: T;
              id?: T;
              label?: T;
              title?: T;
              detail?: T;
              icon?: T;
            };
        solution?:
          | T
          | {
              headline?: T;
              headlineAccent?: T;
              subheadline?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              bottomNote?: T;
            };
      };
  results?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        stats?:
          | T
          | {
              id?: T;
              value?: T;
              suffix?: T;
              label?: T;
              sub?: T;
            };
        trustNote?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  parallax?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        pipelineLabel?: T;
        pipelineValue?: T;
        pipelineDelta?: T;
        bottomLabel?: T;
        bottomDescription?: T;
      };
  whyMiduva?:
    | T
    | {
        eyebrow?: T;
        differentiators?:
          | T
          | {
              num?: T;
              id?: T;
              title?: T;
              subtitle?: T;
              oldWay?: T;
              newWay?: T;
            };
      };
  howItWorks?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        steps?:
          | T
          | {
              num?: T;
              id?: T;
              title?: T;
              description?: T;
              image?: T;
            };
      };
  services?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        ctaLabel?: T;
        ctaHref?: T;
        categories?:
          | T
          | {
              id?: T;
              title?: T;
              image?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
      };
  dashboard?:
    | T
    | {
        urlLabel?: T;
        statusLabel?: T;
        navItems?:
          | T
          | {
              label?: T;
              id?: T;
            };
        clients?:
          | T
          | {
              initials?: T;
              name?: T;
              id?: T;
            };
        eyebrow?: T;
        title?: T;
        kpis?:
          | T
          | {
              label?: T;
              value?: T;
              delta?: T;
              color?: T;
              id?: T;
            };
        chartTitle?: T;
        chartSubtitle?: T;
        funnelTitle?: T;
        funnelStages?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
      };
  growthOs?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        modules?:
          | T
          | {
              name?: T;
              tag?: T;
              description?: T;
              color?: T;
              span?: T;
              visual?: T;
              id?: T;
            };
      };
  freeOffer?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineAccent?: T;
        headlineLine3?: T;
        includes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        trustNote?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        body?: T;
        contactInfo?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        trustStats?:
          | T
          | {
              stat?: T;
              label?: T;
              id?: T;
            };
        formHeadline?: T;
        formSubheadline?: T;
        serviceOptions?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        submitLabel?: T;
        finePrint?: T;
      };
  footer?:
    | T
    | {
        giantBgText?: T;
        heading?: T;
        marqueeItems?:
          | T
          | {
              phrase?: T;
              id?: T;
            };
        primaryCtas?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        secondaryLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        copyright?: T;
        createdByLabel?: T;
      };
  faq?:
    | T
    | {
        items?:
          | T
          | {
              num?: T;
              id?: T;
              question?: T;
              answer?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}